name: Neoload Test Execution
on:
  workflow_dispatch:
jobs:
  run-neoload-test:
    runs-on: neoload5 # Ensure your local runner is 'Active'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     
      - name: Execute NeoLoad Scenario
        shell: powershell
        run: |
          $neoloadPath = 'C:\Program Files\NeoLoad 9.1\bin\NeoLoadCmd.exe'
          $projectPath = "$($env:GITHUB_WORKSPACE)\neoload5.nlp"
          & $neoloadPath -project $projectPath -launch "scenario1" -noGUI
